name: Reusable Environment Setup
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '16'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest