name: Deploy All
on:
  push:
    branches:
      - main
    paths:
      - 'time/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/set-environment.yml
    with:
      node-version: 16

  deploy-project1:
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
      project-path: time-vercel
      project-id: ${{vars.PROJECT_ID}}
      
  deploy-project2:
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
      project-path: time-2
      project-id: ${{vars.PROJECT_ID2}}

  deploy-project3:
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
      project-path: time-3
      project-id: ${{vars.PROJECT_ID3}}
    
