name: Reusable Vercel Deploy
on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      project-id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
       
      - name: Restore cached Vercel CLI
        uses: actions/cache@v3
        with:
         path: ~/.npm-global
         key: ${{ runner.os }}-global-npm-${{ hashFiles('**/package-lock.json') }}
       
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.ORG_ID }}
          VERCEL_PROJECT_ID: ${{ inputs.project-id }}
        run: |
          export PATH=~/.npm-global/bin:$PATH
          cd ${{ inputs.project-path }}
          vercel deploy --token ${VERCEL_TOKEN} --prod --yes