name: Reusable Environment Setup
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '16'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Cache global npm packages
        uses: actions/cache@v3
        with:
         path: ~/.npm-global
         key: ${{ runner.os }}-global-npm-${{ hashFiles('**/package-lock.json') }}
         
      - name: Install Vercel CLI
        run: |
         mkdir -p ~/.npm-global
         npm config set prefix '~/.npm-global'
         export PATH=~/.npm-global/bin:$PATH
         npm install --global vercel@latest
    