name: Deploy Time Project
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VERCEL_TOKEN: ${{env.VERCEL_TOKEN}}
on:
  push:
    branches:
      - main
    paths:
      - 'time/**'  
      - '.github/workflows/time-vercel.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: |
          cd time-vercel
          vercel whoami --token ${VERCEL_TOKEN}
          echo "VERCEL_TOKEN=${VERCEL_TOKEN}"
          npx vercel --prod --yes