name: Deploy Time Project
on:
  push:
    branches:
      - main
    paths:
      - 'time/**'  
      - '.github/workflows/time-vercel.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: NlAVteTarvIi5LcJ6lulAgP1
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }} 
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }} 
        run: |
          cd time-vercel
          vercel whoami --token ${VERCEL_TOKEN}
          echo "VERCEL_TOKEN=${VERCEL_TOKEN}"
          vercel login --token ${VERCEL_TOKEN}
          npx vercel --prod --yes