name: Deploy Project 3
run-name: "Project 3: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:    
      - main
    paths:
     - 'time-3/**'
     - '.github/workflows/time-3.yml'
     - '.github/workflows/set-environment.yml'
     - '.github/workflows/deploy-base.yml'
  workflow_dispatch:
jobs:
  setup:
   name: Setup (${{ github.event.head_commit.message }})
   uses: ./.github/workflows/set-environment.yml
   with:
     node-version: 16
  deploy:
    name: Deploy Project 3 - ${{ github.event.head_commit.message }}
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
     project-path: time-3
     project-id: ${{vars.PROJECT_ID3}}