name: Deploy Project 1
on:
  push:
    branches:    
      - main
    paths:
     - 'time-1/**'
     - '.github/workflows/time-1.yml'
     - '.github/workflows/set-environment.yml'
     - '.github/workflows/deploy-base.yml'
  workflow_dispatch:
jobs:
  setup:
   uses: ./.github/workflows/set-environment.yml
   with:
     node-version: 16
  deploy:
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
     project-path: time-1
     project-id: ${{vars.PROJECT_ID1}}