name: Deploy Project 2
run-name: "Project 2: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:    
      - main
    paths:
     - 'time-2/**'
     - '.github/workflows/time-2.yml'
     - '.github/workflows/set-environment.yml'
     - '.github/workflows/deploy-base.yml'
  workflow_dispatch:
jobs:
  setup:
    name: Setup (${{ github.event.head_commit.message }})
    uses: ./.github/workflows/set-environment.yml
    with:
      node-version: 16
  deploy:
    name: Deploy Project 2 - ${{ github.event.head_commit.message }}
    needs: setup
    uses: ./.github/workflows/deploy-base.yml
    with:
     project-path: time-2
     project-id: ${{vars.PROJECT_ID2}}